server:
  port: 8070

spring:
  datasource:
    url: jdbc:h2:mem:ciddb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.cidapp: DEBUG

# External App Configuration
external:
  banking-app:
    url: http://localhost:8081/api/banking
    timeout: 30000
  third-party:
    reconciliation-url: http://localhost:8082/api/reconcile
    timeout: 30000
